### ISSUE TITLE
miss some files

### ISSUE THREAD

**Issue by SY-XU** [holysjl/Course_Arranging_System#1]
Hello! I found some files are not in the path which named "yage.h"
thank you!

**Comment by jialiangs** [comment]
Actually, yage is a graph lib developed by my classmates. And I do not have its source code. I just uploaded my code to Github to store my project task, and have never considered being reused by others. Sorry about that!

**Comment by SY-XU** [comment]
It doesn't matter. Actually, I'm very glad that you can reply to me, because I'm making a 
Automatic course arranging system recently, so I'm collecting algorithms on GitHub.

**Comment by jialiangs** [comment]
My project is a very simple algorithm I wrote when I was a fresh student. So I think you can find another course arranging algorithms.
